version: "3.8"

services:
  # Production build
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped

  # Development server with hot reloading
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable file watching in Docker
      - VITE_HOST=http://localhost:8081
      - VITE_COOKI_EXPIRED=1 # day
    restart: unless-stopped